[tool.poetry]
name = "timeball"
version = "0.1.0"
description = ""
authors = ["David Roher <davidroher@davids-air.home>"]

[tool.poetry.dependencies]
python = "^3.9"
dbt-core = "^1.0.0"
dbt-duckdb = "^1.1"
duckdb = "0.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
