[tool.poetry]
name = "timeball"
version = "0.1.0"
description = ""
authors = ["David Roher <davidroher@davids-air.home>"]

[tool.poetry.dependencies]
python = "^3.10.0,<3.11"

dbt-core = "~1.6.0"
dbt-duckdb = "~1.6.0"
dbt-coves = "~1.6.0"
duckdb = "0.9.0"

tensorflow = "~2.13.0"
tensorflow-metal = {version = "~1.0.1", optional = true}
tensorflow-macos = { version = "~2.13.0", platform = "darwin", markers = "platform_machine=='arm64'" }

numpy = "1.24.3"
pandas = "~2.0.3"
polars = "^0.19.3"
pyarrow = "~13.0.0"

[tool.poetry.dev-dependencies]
sqlfluff = "^2.3.1"
sqlfluff-templater-dbt = "^2.3.1"
ipykernel = "^6.25.2"

[tool.poetry.group.extras.dependencies]
tensorflow-metal = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
