version: 2

sources:
  - name: box_score
    tables:
      - name: box_score_batting_lines
      - name: box_score_caught_stealing
      - name: box_score_double_plays
      - name: box_score_fielding_lines
      - name: box_score_game
      - name: box_score_hit_by_pitches
      - name: box_score_home_runs
      - name: box_score_pinch_hitting_lines
      - name: box_score_pinch_running_lines
      - name: box_score_pitching_lines
      - name: box_score_stolen_bases
      - name: box_score_team
      - name: box_score_team_batting_lines
      - name: box_score_team_fielding_lines
      - name: box_score_team_miscellaneous_lines
      - name: box_score_triple_plays
      - name: box_score_umpire
  - name: event
    tables:
      - name: event
      - name: event_baserunning_advance_attempt
      - name: event_baserunning_play
      - name: event_fielding_play
      - name: event_flag
      - name: event_hit_location
      - name: event_out
      - name: event_pitch
      - name: event_plate_appearance
      - name: event_starting_base_state
  - name: game
    tables:
      - name: game
      - name: game_fielding_appearance
      - name: game_lineup_appearance
      - name: game_team
      - name: game_umpire
  - name: misc
    tables:
      - name: franchise
      - name: gamelog
      - name: park
      - name: people
      - name: roster
      - name: schedule